server:
  port: 8084

spring:
  application:
    name: ms-progresso

  # Configuração do MongoDB
  data:
    mongodb:
      uri: mongodb://mongo:27017/db_progresso

  # Configuração do RabbitMQ
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: dac
    password: dac