server:
  port: 8085

spring:
  application:
    name: ms-progresso

  # Configuração do MongoDB
  data:
    mongodb:
      uri: mongodb://dac:dac@mongo:27017/db_progresso?authSource=admin

  # Configuração do RabbitMQ
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: dac
    password: dac