version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dac
      MONGO_INITDB_ROOT_PASSWORD: dac
      MONGO_INITDB_DATABASE: db_autenticacao
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - ms-autenticacao
      - ms-usuarios
      - ms-cursos
      - ms-avaliacoes
      - ms-progresso
      - ms-gamificacao
      - ms-notificacoes

  ms-autenticacao:
    build: ./ms-autenticacao
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/ms-autenticacao
    depends_on:
      - mongo

  ms-usuarios:
    build: ./ms-usuarios
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  ms-cursos:
    build: ./ms-cursos
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ms-cursos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  ms-avaliacoes:
    build: ./ms-avaliacoes
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ms-avaliacoes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  ms-progresso:
    build: ./ms-progresso
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ms-progresso
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  ms-gamificacao:
    build: ./ms-gamificacao
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ms-gamificacao
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

  ms-notificacoes:
    build: ./ms-notificacoes
    ports:
      - "8087:8087"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/ms-notificacoes
    depends_on:
      - mongo

volumes:
  pgdata:
  mongodata:

