server:
  port: 8087

spring:
  application:
    name: ms-notificacoes

  # Configuração do MongoDB (Banco de Dados)
  data:
    mongodb:
      # Conecta no container 'mongo' definido no docker-compose
      uri: mongodb://dac:dac@mongo:27017/db_notificacoes?authSource=admin

  # Configuração do RabbitMQ (Mensageria)
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: dac
    password: dac

  # Configuração de E-mail (Exemplo com Gmail)
  # DICA: Para funcionar com Gmail, gere uma "Senha de App" na sua conta Google.
  mail:
    host: smtp.gmail.com
    port: 587
    username: vineonis@gmail.com
    password: rvosbsjicsnzwbwx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true