server:
  port: 8085 # Porta já definida no docker-compose

spring:
  application:
    name: ms-gamificacao

  # Configuração do MongoDB
  data:
    mongodb:
      uri: mongodb://mongo:27017/db_gamificacao

  # Configuração do RabbitMQ
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: dac
    password: dac