server:
  port: 8081

spring:
  application:
    name: ms-autenticacao

  # Conexão MongoDB
  data:
    mongodb:
      uri: mongodb://dac:dac@mongo:27017/db_autenticacao?authSource=admin

  # Conexão RabbitMQ
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: dac
    password: dac

jwt:
  secret: "bWluaGFTZW5oYVN1cGVyU2VjcmV0YURlMzJCeXRlcyEh"
  expiration: 28800000
