server:
  port: 8081

spring:
  application:
    name: ms-autenticacao
  data:
    mongodb:
      uri: mongodb://dac:dac@mongo:27017/db_autenticacao?authSource=admin

jwt:
  secret: "c2VuaGFTZWNyZXRhRG8tUHJvamV0by1EQUMtMjAyNQ=="
  expiration: 28800000