server:
  port: 8081 # A porta do teu microsservi√ßo

spring:
  application:
    name: ms-autenticacao

  datasource:
    url: jdbc:postgresql://postgres:5432/db_usuarios
    username: dac
    password: dac
  jpa:
    hibernate:
      ddl-auto: update # Atualiza o schema do banco automaticamente
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: arthurdiasbaptista@gmail.com
    password: flrw elqg tobs chjt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: "c2VuaGFTZWNyZXRhRG8tUHJvamV0by1EQUMtMjAyNQ=="
  expiration: 28800000