server:
  port: 8081

spring:
  application:
    name: ms-autenticacao

  # REMOVER configuração do PostgreSQL
  # ADICIONAR configuração do MongoDB
  data:
    mongodb:
      uri: mongodb://dac:dac@mongo:27017/db_autenticacao?authSource=admin

  mail:
    host: smtp.gmail.com
    port: 587
    username: arthurdiasbaptista@gmail.com
    password: flrw elqg tobs chjt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: "bWluaGFTZW5oYVN1cGVyU2VjcmV0YURlMzJCeXRlcyEh"
  expiration: 28800000
